### ISSUE TITLE
Write Sample Simulink Program

### ISSUE THREAD

**Issue by xmarkalex** [maraco51693/CP-FES-Cycling-#11]
Should be able to:
- read a variable from the matlab workspace
- Apply some sort of function to it
- Output a result

**Comment by sebowers** [comment]
Small piece of code written to read in an excel file. The code multiples the first column of the Excel file by 2 and the second column divides the numbers by 2. The results are then outputted to a text document. 

[output.txt](https://github.com/maraco51693/CP-FES-Cycling-/files/901644/output.txt)

[CISC475Test.xlsx](https://github.com/maraco51693/CP-FES-Cycling-/files/901643/CISC475Test.xlsx)

`data = xlsread('CISC475Test.xlsx')
firstColumn = data(:,1)
secondColumn = data(:,2)
newfirstcolumn = firstColumn*2;
newsecondcolumn = secondColumn/2;
output = fopen('output.txt','w');
fprintf(output,'%6.2f %12.8f\n',newfirstcolumn);
fprintf(output,'%6.2f %12.8f\n',newsecondcolumn);
fclose(output);
type output.txt`

**Comment by xmarkalex** [comment]
https://github.com/maraco51693/CP-FES-Cycling-/tree/master/Tests/Sample%20Simulink

reads srm_raw data 
displays the data point in its respective time up to 14819 seconds
